INSERT INTO genre (name, description) values ('Комедия','призвана вызвать смех и развлечь зрителей');
INSERT INTO genre (name, description) values ('Драма','фокусируется на эмоциональных аспектах и конфликтах персонажей');
INSERT INTO genre (name, description) values ('Мультфильм','');
INSERT INTO genre (name, description) values ('Триллер','');
INSERT INTO genre (name, description) values ('Документальный','фильм, основанные на реальных событиях и фактах, часто с использованием интервью и архивных материалов');
INSERT INTO genre (name, description) values ('Боевик','сосредотачивается на динамичных действиях и борьбе');
--INSERT INTO genre (name, description) values ('ужасы','создают атмосферу страха и напряжения');
--INSERT INTO genre (name, description) values ('детектив','фильм, в котором расследуются преступления, часто с участием сыщиков и загадочных обстоятельств');
INSERT INTO rating (name, description) values ('G','General Audiences.Фильм подходит для любой аудитории, включая детей');
INSERT INTO rating (name, description) values ('PG','Parental Guidance Suggested. Рекомендуется родительское сопровождение, так как фильм может содержать некоторые материалы, не подходящие для маленьких детей');
INSERT INTO rating (name, description) values ('PG-13','Parents Strongly Cautioned. Просмотр не рекомендуется детям до 13 лет, так как фильм может содержать материалы, которые могут быть неприемлемы для младших детей');
INSERT INTO rating (name, description) values ('R','Restricted. Лицам до 17 лет требуется сопровождение родителя или взрослого опекуна');
INSERT INTO rating (name, description) values ('NC-17','No One 17 & Under Admitted. Фильм предназначен только для взрослых, лицам до 17 лет вход запрещен.');
