INSERT INTO genre (name, description) values ('драма','фокусируется на эмоциональных аспектах и конфликтах персонажей');
INSERT INTO genre (name, description) values ('комедия','призвана вызвать смех и развлечь зрителей');
INSERT INTO genre (name, description) values ('ужасы','создают атмосферу страха и напряжения');
INSERT INTO genre (name, description) values ('фантастика','включает элементы научной фантастики и фантазии');
INSERT INTO genre (name, description) values ('боевик','сосредотачивается на динамичных действиях и борьбе');
INSERT INTO genre (name, description) values ('детектив','фильм, в котором расследуются преступления, часто с участием сыщиков и загадочных обстоятельств');
INSERT INTO genre (name, description) values ('приключения','фильм с захватывающим сюжетом, напряженным действием и увлекательными событиями');
INSERT INTO genre (name, description) values ('документальный','фильм, основанные на реальных событиях и фактах, часто с использованием интервью и архивных материалов');
INSERT INTO rating (code, description) values ('G','General Audiences.Фильм подходит для любой аудитории, включая детей');
INSERT INTO rating (code, description) values ('PG','Parental Guidance Suggested. Рекомендуется родительское сопровождение, так как фильм может содержать некоторые материалы, не подходящие для маленьких детей');
INSERT INTO rating (code, description) values ('PG-13','Parents Strongly Cautioned. Просмотр не рекомендуется детям до 13 лет, так как фильм может содержать материалы, которые могут быть неприемлемы для младших детей');
INSERT INTO rating (code, description) values ('R','Restricted. Лицам до 17 лет требуется сопровождение родителя или взрослого опекуна');
INSERT INTO rating (code, description) values ('NC-17','No One 17 & Under Admitted. Фильм предназначен только для взрослых, лицам до 17 лет вход запрещен.');
